[
    {
        "domain": ".shopee.vn",
        "expirationDate": 1669632825,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_fbp",
        "path": "/",
        "sameSite": "lax",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "fb.1.1661852255623.549421769"
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 1669628255,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_gcl_au",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "1.1.1658920275.1661852256"
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 1661943226,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_gid",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GA1.2.600469699.1661852257"
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 1661858626,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_hjAbsoluteSessionInProgress",
        "path": "/",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "1"
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 1661858086,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_hjFirstSeen",
        "path": "/",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "1"
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 1661858626,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_hjSession_868286",
        "path": "/",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "eyJpZCI6IjgyOWE5MThlLWIyYzQtNDMxNS04NTM1LTk2MGFjM2RhZThkZiIsImNyZWF0ZWQiOjE2NjE4NTIyNTc0NjgsImluU2FtcGxlIjpmYWxzZX0="
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 1696412255,
        "hostOnly": false,
        "httpOnly": true,
        "name": "REC_T_ID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "61a4e540-2847-11ed-834c-2cea7fa52b50"
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 1696412256,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SPC_F",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "Zha2bTMeVEJtuRGTPh6Qx6qtUxAJ9uO0"
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 1661943226.501644,
        "hostOnly": false,
        "httpOnly": true,
        "name": "SPC_SI",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "mall.PJadg9ONSRVnFTRKgV8ygM2DiRILPebo"
    },
    {
        "domain": "shopee.vn",
        "hostOnly": true,
        "httpOnly": false,
        "name": "__LOCALE__null",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "VN"
    },
    {
        "domain": "shopee.vn",
        "hostOnly": true,
        "httpOnly": false,
        "name": "_QPWSDCXHZQA",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "6af4d198-bb5d-426a-ac7a-d96f28f5732a"
    },
    {
        "domain": "shopee.vn",
        "hostOnly": true,
        "httpOnly": false,
        "name": "csrftoken",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "BkZ19uLbgA8e00riLTW934OVxeAumDnK"
    },
    {
        "domain": "shopee.vn",
        "expirationDate": 1696412256,
        "hostOnly": true,
        "httpOnly": true,
        "name": "REC_T_ID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "61a6c1fa-2847-11ed-8e0b-4ee00822f83f"
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 1693392826,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_hjSessionUser_868286",
        "path": "/",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "eyJpZCI6IjhmYjQwNTYwLTU2ZGUtNTFmNy05ZDQ3LWE1ZDMwNDJhNmFkNCIsImNyZWF0ZWQiOjE2NjE4NTIyNTcyMDIsImV4aXN0aW5nIjp0cnVlfQ=="
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 1661859458,
        "hostOnly": false,
        "httpOnly": false,
        "name": "AMP_TOKEN",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "%24NOT_FOUND"
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 1696416377.02876,
        "hostOnly": false,
        "httpOnly": false,
        "name": "G_ENABLED_IDPS",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "google"
    },
    {
        "domain": ".shopee.vn",
        "hostOnly": false,
        "httpOnly": false,
        "name": "G_AUTHUSER_H",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": true,
        "storeId": "0",
        "value": "0"
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 1696416826.501667,
        "hostOnly": false,
        "httpOnly": true,
        "name": "SPC_ST",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": ".a1pMTjJoNVQzenk2UmhieBC6vVe2dssilFqGyawwn1h8O24pCh+wVM1GXcmp0nUjW41i3ewRsvohqhB2dtHHKJ4swVezLTsMA/pqwF4CqjZmBJhjZQPuWOSdJtHtYhXH5iwNTNPn6xfCeqHP9+p+XiYoWNzb2wsDmrlfUhrkhO4mEobcler3G/d+jpOkZHxK+WnsWDcxNks1Y6okHnSoDA=="
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 1696416380.955271,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SPC_CLIENTID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "WmhhMmJUTWVWRUp0xcrhsbavvhpdajdx"
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 1696416826.501688,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SPC_U",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "528412036"
    },
    {
        "domain": "shopee.vn",
        "expirationDate": 1696416825.076125,
        "hostOnly": true,
        "httpOnly": false,
        "name": "SPC_T_ID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "\"QYRFIlykTVW5unv/jByrPrim9RZj30MPFhkLxgUylTBk+BC+s7hARJbJNXDxGqZkFkF5rJje6SPypAGId5ChpLqMeIuHqY+xGnGSByC5dKA=\""
    },
    {
        "domain": "shopee.vn",
        "expirationDate": 1696416825.076088,
        "hostOnly": true,
        "httpOnly": false,
        "name": "SPC_T_IV",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "\"ygoYMPHwXH4KrxxTJgrqDg==\""
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 1696416826.501757,
        "hostOnly": false,
        "httpOnly": true,
        "name": "SPC_T_ID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "QYRFIlykTVW5unv/jByrPrim9RZj30MPFhkLxgUylTBk+BC+s7hARJbJNXDxGqZkFkF5rJje6SPypAGId5ChpLqMeIuHqY+xGnGSByC5dKA="
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 1696416826.501577,
        "hostOnly": false,
        "httpOnly": true,
        "name": "SPC_T_IV",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "ygoYMPHwXH4KrxxTJgrqDg=="
    },
    {
        "domain": "shopee.vn",
        "hostOnly": true,
        "httpOnly": false,
        "name": "SPC_IA",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "1"
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 1696416826.501724,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SPC_R_T_ID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "QYRFIlykTVW5unv/jByrPrim9RZj30MPFhkLxgUylTBk+BC+s7hARJbJNXDxGqZkFkF5rJje6SPypAGId5ChpLqMeIuHqY+xGnGSByC5dKA="
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 1696416826.501741,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SPC_R_T_IV",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "ygoYMPHwXH4KrxxTJgrqDg=="
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 1696416826.501705,
        "hostOnly": false,
        "httpOnly": true,
        "name": "SPC_EC",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "dEh4Y0hxc2pSUmJTOWxlRxLhJUhTjaIzmbujxRtTkbeXkBR3IuFoRFutnouFe7JgQFNpKZjkIdGym9+vQ4jRw1uom9+buJ2Cpv2B+qk5V5B4tWAOuZ5rdPl1tB4sRohzDqzWkLQAZKgZyRISfaroQX13fGkWHRoX1x4dmLoasO0="
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 1696416826.678653,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga_M32T05RVZT",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GS1.1.1661843932.16.1.1661856826.58.0.0"
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 1696416826.752396,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GA1.2.1585690644.1661852257"
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 1661856886,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_dc_gtm_UA-61914164-6",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "1"
    },
    {
        "domain": "shopee.vn",
        "expirationDate": 1661856946,
        "hostOnly": true,
        "httpOnly": false,
        "name": "_hjIncludedInSessionSample",
        "path": "/",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "0"
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 1696020827,
        "hostOnly": false,
        "httpOnly": false,
        "name": "cto_bundle",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "bKQleF9WcDJzdHVGUGNHQzRVMlpLVjBhZXpkdGd2NHl0TiUyRmRXalVwRWc5SzlhSVNTVVFMWmY4SVR3M3c3N255SFoxU2VmSDR3SHolMkJMSiUyQkx6WTElMkI3N1ZON05Fdmk3QWFzbHNEJTJCZTkzVWVYNzExSEd3SU9pMlNKWjh5TXhhOG5QJTJGRllQd0gxSVZLOXRHNU1pb2owJTJCRlMlMkJES3hBJTNEJTNE"
    },
    {
        "domain": "shopee.vn",
        "hostOnly": true,
        "httpOnly": false,
        "name": "shopee_webUnique_ccd",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "vwMk86Vqt5mIj8f32Cuyew%3D%3D%7CJ2Rgegw2RvrLERVVg1TwhUx%2BUEstICEtK5lfqa4q1NM64tZs8UrSZd6wwKYgVewRTIS0dIsyMSnJqNzk87u0l9LYmq8s%7CIY1u69QYuUyoWiyM%7C05%7C3"
    }
]

hanlde = data.map((e,i) => {
    if(i<data.length - 1) {
        return `${e.name}=${e.value};`
    }
    else {
return `${e.name}=${e.value}`
    }
})
hanlde.join("")
